<a href="https://colab.research.google.com/github/elmaazouziyassine/Machine_Learning_Python/blob/master/7_Deep%20Learning/Artificial%20Neural%20Networks%20(ANN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Artificial Neural Networks (ANN)**



### **Data Preprocessing**




In [0]:
# Import the needed libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [0]:
# Installing Theano
#pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
#Install Tensorflow from the website: https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html

# Installing Keras
#pip install --upgrade keras

In [52]:
# Import dataset
dataset = 'https://raw.githubusercontent.com/elmaazouziyassine/Machine_Learning_Python/master/datasets/bank_customers.csv'
data = pd.read_csv(dataset)
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [53]:
data.count()

RowNumber          10000
CustomerId         10000
Surname            10000
CreditScore        10000
Geography          10000
Gender             10000
Age                10000
Tenure             10000
Balance            10000
NumOfProducts      10000
HasCrCard          10000
IsActiveMember     10000
EstimatedSalary    10000
Exited             10000
dtype: int64

In [0]:
# Separate Features Variables from Target Variable
X = data.iloc[:, 3:13].values
y = data.iloc[:, 13].values

In [55]:
# Encode "Geography" & "Gender" variables
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

print('--- X Geography ---')
print(X)

print('--- LabelEncoder Geography ---')
le_1 = LabelEncoder()
X[:, 1] = le_1.fit_transform(X[:, 1])

print('--- LabelEncoder Gender ---')
le_2 = LabelEncoder()
X[:, 2] = le_2.fit_transform(X[:, 2])
print(X)

print('--- OneHotEncoder Geography ---')
ct = ColumnTransformer([('Geography', OneHotEncoder(), [1])], remainder='passthrough')
X = ct.fit_transform(X) #.toarray()
print(X)

# remove 1 dummy variable related to Geography
X = X[:, 1:]
print(X[0,:])

--- X Geography ---
[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
--- LabelEncoder Geography ---
--- LabelEncoder Gender ---
[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]
--- OneHotEncoder Geography ---
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]
[0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]


In [0]:
# Split the Dataset into Training Set and Test Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0) # 20% of data for test

In [0]:
# Apply Feature Scaling
from sklearn.preprocessing import StandardScaler
scale_X = StandardScaler()
X_train = scale_X.fit_transform(X_train)
X_test = scale_X.transform(X_test)

### **Apply the model to the training dataset**



In [0]:
# Importing the Keras libraries and packages
import keras # will help build the neural network based on TensorFlow
from keras.models import Sequential
from keras.layers import Dense

In [59]:
# Initialising the ANN
classifier = Sequential()  # Sequence of layers

# Adding the input layer and the first hidden layer (dense funtion will take in charge the initialisation of the weights)
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  app.launch_new_instance()


Epoch 1/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.4937 - acc: 0.7952
Epoch 2/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.4282 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.4235 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.4191 - acc: 0.8097
Epoch 5/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.4165 - acc: 0.8256
Epoch 6/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.4148 - acc: 0.8289
Epoch 7/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.4136 - acc: 0.8311
Epoch 8/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4122 - acc: 0.8319
Epoch 9/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.4108 - acc: 0.8325
Epoch 10/100
8000/8000 [==============================] - 1s 121us/step - loss: 0.4105 - acc: 0.8324

### **Predict test set results**

In [0]:
y_pred = classifier.predict(X_test)  # y_pred is a probability
y_pred = (y_pred > 0.5)  # because we used the sigmoid as an activation function

### **Visualize results**

### **Test the performance of the model**

Compute **Confusion Matrix** to evaluate the accuracy of a classification


In [61]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1538,   57],
       [ 259,  146]])

In [63]:
accuracy = (1538+146)/2000
accuracy

0.842